### ISSUE TITLE
Winget not finding apps on the repo - System context?

### ISSUE THREAD

**Issue by durrante** [Romanitho/WingetIntunePackager#17]
Hi there,

First of all, many thanks for your efforts on this, I am using the wingetIntunePackager application and I am running into the below issues when using Windows Autopilot for applications in system context, this is the error:

![image](https://github.com/Romanitho/WingetIntunePackager/assets/64601521/06e45d91-f0a5-46b3-98b4-f3581eb6b302)

This is my application installation cmdlet with Windows Package Manager as a dependency:

`"%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File winget-install.ps1 -AppIDs "Google.Chrome"`

![image](https://github.com/Romanitho/WingetIntunePackager/assets/64601521/5a980c70-6aa4-4782-a24f-4cb1e032cf31)

Is there anything that I may have missed to get this to work in system context? I cannot see what I am doing wrong, the end user does not have admin rights, but I thought doing it this way would resolve this.

Many thanks!

**Comment by KnifMelti** [comment]
Delete the "fnutts": `-AppIDs Google.Chrome`

**Comment by durrante** [comment]
> Delete the "fnutts": `-AppIDs Google.Chrome`

Hi there, I tried this after seeing your other comments, no change I'm afraid, I think it may be due to a slightly older version of Winget, but I'm not sure! This is my latest installation command:

"%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File winget-install.ps1 -AppIDs Google.Chrome

**Comment by KnifMelti** [comment]
Strange, no clue then @Romanitho...

**Comment by durrante** [comment]
UPDATE @Romanitho , updated Winget to 1.20+ but issue persists: 

![image](https://github.com/Romanitho/WingetIntunePackager/assets/64601521/c56912d5-d23c-47b2-906e-90c9ddf59361)

**Comment by Romanitho** [comment]
Hi, sorry, just back from holidays 😊
They might have change something with latest winget versions... I probably need to adapt https://github.com/Romanitho/Winget-Install/blob/main/winget-install.ps1

**Comment by Romanitho** [comment]
Could you make a test with this version please ? 
https://github.com/Romanitho/WingetIntunePackager/releases/tag/v1.1.6

**Comment by durrante** [comment]
> Could you make a test with this version please ? https://github.com/Romanitho/WingetIntunePackager/releases/tag/v1.1.6

Hi there, many thanks for looking into this, I will test this tomorrow and report back!

**Comment by Romanitho** [comment]
hi, could you share the log file please? I would like to check the entire winget cmd line used.

**Comment by durrante** [comment]
Sure @Romanitho, here you go. 
[install.log.txt](https://github.com/Romanitho/WingetIntunePackager/files/12536999/install.log.txt)

the installation command from Intune is: "%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File winget-install.ps1 -AppIDs "Google.Chrome", I've not changed anything other than adding Windows Package Manager as a dependency, that ensures that the 1.20.2201.0 version of appinstaller is present.

**Comment by Romanitho** [comment]
Hello,
I just encounter the same issue to one of my customers. Winget was not in the latest version during autopilot.

**Comment by durrante** [comment]
@Romanitho, Strange, my winget version is pretty recent (see above screenshot I sent to you), it was released last month https://github.com/microsoft/winget-cli/releases/tag/v1.5.2201

So I'm not sure what's going on with your solution as it seems like in my environment anyway that I have a very recent version of winget, so no idea why it isn't finding the applications to install.

**Comment by durrante** [comment]
I am going to test using this version that was released two days ago: https://github.com/microsoft/winget-cli/releases/tag/v1.6.2482

**Comment by Romanitho** [comment]
you're right. I put WAU as dependence of all my packages as well, don't know if that helps 😅😅

**Comment by durrante** [comment]
Are you able to reproduce my issue? e.g. Apps not available in the winget repo when ran via Autopilot \ system context? Wondering if it's just me!

**Comment by Romanitho** [comment]
I'll make a new test in few minutes

**Comment by durrante** [comment]
Okay great, I am available all afternoon for testing, if needed.

**Comment by Romanitho** [comment]
in my lab, win11 VM, autopilot goes till the end without any issue. I packaged WAU in latest version and is set to required to all my winget install packages.

**Comment by durrante** [comment]
@Romanitho - Oh, I wonder what the difference is between you and me then, what version of Windows Package Manager are you running? Mine is 1.20.2201.0 and have that as a dependency and then I use your WingetIntunePackager script to create the installations, I don't have any other policies or profiles installed.

I'm lost as to why yours works and mine doesn't. I'm running Windows 11, fully patched.

Maybe I am missing something then!

**Comment by Romanitho** [comment]
I'm installing other apps, but they all work. Try installing WAU as dependence to be sure on testing machine.

**Comment by Romanitho** [comment]
You could give this a try:
https://github.com/Romanitho/Winget-AutoUpdate/discussions/88#discussioncomment-2849475
Of course, create an intunewim package first with the sources.

I agree, we need to make a better documentation on Intune implementation 😊

**Comment by Romanitho** [comment]
Closed due to inactivity
