### ISSUE TITLE
Older version IntuneWin32App Module

### ISSUE THREAD

**Issue by GertonD** [Romanitho/WingetIntunePackager#19]
I had an older version IntuneWin32App Module already installed on my machine which resulted in not being able to connect to tenants.
I solved it by manually running the module install command with the addition of -AllowClobber.

**Comment by Romanitho** [comment]
this is caused by multiple versions of IntuneWin32App ?

**Comment by GertonD** [comment]
The version I had previously installed did not contain the function Connect-MSIntuneGraph which was added in version 1.2.0.

**Comment by GertonD** [comment]
Yes, you could builtin a version check but I doubt there will be a lot of people having this old version installed and if they have they could reference this closed issue.

**Comment by Romanitho** [comment]
It's a good idea. If you have an idea, feel free to implement the code to get credited 👌🏼

**Comment by Romanitho** [comment]
Should be fixed #25
