### ISSUE TITLE
Nothing happens after hitting CREATE button?

### ISSUE THREAD

**Issue by ztrhgf** [Romanitho/WingetIntunePackager#22]
Hi,
is there any log where I can check what is happening in the background when CREATE button is pushed?

I tried to create 7zip package twice:
1. first attempt when add to WAU allow list was checked lead to unresponsive gui
2. second attempt without WAU whitelist checked lead to "nothing". When I push CREATE button nothing happens except GUI refreshes to "right after the launch state" except I can see I am connected to my tenant. 

Used account has admin permissions over Intune btw.

**Comment by IamTBUCK** [comment]
I'm seeing the exact same thing as you. First attempt it went to 'unresponsive' after letting it sit for over 20 minutes. Subsequent attempts just have the small window pop-up for a split second before disappearing and clearing everything but the Intune ID and connection status

**Comment by Romanitho** [comment]
There is a bug I try to understand with the `New-IntuneWin32AppPackage` command line 505

**Comment by Romanitho** [comment]
should be fixed now
