### ISSUE TITLE
Winget Intune Packager not finding apps

### ISSUE THREAD

**Issue by wthrwthr** [Romanitho/WingetIntunePackager#6]
I am starting the Intune packager by running the provided script, the GUI pulls up fine and everything, but no matter what I type I get "no applications found". Is there something I am missing? Your other app, when run as a powershell script, was able to find the apps just fine, so I assume it's not my AV? We use windows defender.

**Comment by Romanitho** [comment]
it's working on my side. Run it without admin rights, to be sure it uses Winget from your user account.

**Comment by wthrwthr** [comment]
This helped, thanks!! Awesome tool btw, let me know if I can contribute anything!

**Comment by Romanitho** [comment]
Thanks for your comment. Any reported bug, or if PowerShell skill to improve the project would be appreciated :)
