### ISSUE TITLE
Purpose of TenantID?

### ISSUE THREAD

**Issue by JayG30** [Romanitho/WingetIntunePackager#9]
Now that I've got the application to run, I'm wondering what is the purpose of entering the Teant ID? I figured it would connect to the tenant and create the win32 app in the tenant. However that doesn't seem to be the case. Currently all I'm seeing is that it creates the intunewin and detect files in C:\ProgramData\WingetIntunePackagerTemp\Winget-Install-1.10.1\.

Thanks.

**Comment by Romanitho** [comment]
Not sure to get you. This project is just built to simplify the way I use https://github.com/Romanitho/Winget-Install. It allows me to create winget apps based on my other project in few clicks

**Comment by JayG30** [comment]
> Not sure to get you. This project is just built to simplify the way I use https://github.com/Romanitho/Winget-Install. It allows me to create winget apps based on my other project in few clicks

Then what's the point of entered the Azure tenant ID to generate the intunewin? Pretty sure I've never needed my tenant ID for that.

And what's the point of the override and additional arguments? Doesn't look like they are inserted anywhere in the PowerShell scripts.

**Comment by Romanitho** [comment]
because it is needed to connect to Intune to create the app and upload the intunwin...

**Comment by Romanitho** [comment]
the arguments are put in the install command line

**Comment by JayG30** [comment]
> because it is needed to connect to Intune to create the app and upload the intunwin...

Okay, that's what I thought was going to happen. That it would upload the intunewin to Intune and create the App. But it doesn't do that for me at all.

It says it's connected and I see the intunewin app created in the folder under C:\programdata. I can copy it out and manually upload to Intune to create the win32 app. But it doesn't create anything in Intune on its own...

**Comment by JayG30** [comment]
> the arguments are put in the install command line

That would make sense of when I ran it it actually created the win32 app within my Intune tenant. But since that's not happening for me it seemed pointless.

Perhaps I'm missing something in the setup/install process? A prerequisite? I simply downloaded the release and ran the .EXE. It ran through some PowerShell and the app opens. Searching apps, the check button, and the tenant connect work. Create generates the files on the programdata folder. But nothing created within the Intune portal.

**Comment by Romanitho** [comment]
maybe permissions on intune side. As this project is based on https://github.com/MSEndpointMgr/IntuneWin32App

**Comment by Romanitho** [comment]
but thanks to try this tool as it can help to detect bugs

**Comment by JayG30** [comment]
> maybe permissions on intune side. As this project is based on https://github.com/MSEndpointMgr/IntuneWin32App

Thanks! I will look there and see what I can find. I'm connecting as global admin. And I was able to perform similar app creation with some other PowerShell scripts. So not sure what's going on.

I'll download that package of tools tomorrow and see how they work on their own.

**Comment by Romanitho** [comment]
Thanks. Give me your feedback as it can help me to improve the stuff

**Comment by JayG30** [comment]
I deleted contents in %temp% folder, which appears to be where the IntuneWinAppUtil.exe gets downloaded. And now the GUI goes unresponsive and nothing gets created within Intune.

![intune packager](https://github.com/Romanitho/WingetIntunePackager/assets/1624123/2ec73d8c-fa95-49c3-9443-a8e4836523f7)

If I force close the application and then relaunch it and try again it goes back to the previous behavior I mentioned where nothing is created in Intune and clicking create causes a quick popup about creating the App in Intune and the GUI content cleared out after.

**Comment by JayG30** [comment]
I think I might have found a problem.
In WingetIntunePackager.ps1 there is [this line (513)](https://github.com/Romanitho/WingetIntunePackager/blob/823ca6e0b4c30fe9eaee4c059335b60ac9dcd904/sources/WingetIntunePackager.ps1#L513).
```powershell
$RequirementRule = New-IntuneWin32AppRequirementRule -Architecture "All" -MinimumSupportedWindowsRelease "2004"
``` 
If you try to run this against the current version of IntuneWin32App it will fail with this error message;
```powershell
PS C:\WINDOWS\system32> New-IntuneWin32AppRequirementRule -Architecture "all" -MinimumSupportedWindowsRelease "2004"
New-IntuneWin32AppRequirementRule : Cannot validate argument on parameter 'MinimumSupportedWindowsRelease'. The argument "2004" does not belong to the set
"W10_1607,W10_1703,W10_1709,W10_1803,W10_1809,W10_1903,W10_1909,W10_2004,W10_20H2,W10_21H1,W10_21H2,W10_22H2,W11_21H2,W11_22H2" specified by the ValidateSet
attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:87
+ ... rementRule -Architecture "all" -MinimumSupportedWindowsRelease "2004"
+                                                                    ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-IntuneWin32AppRequirementRule], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-IntuneWin32AppRequirementRule
``` 
So I believe this needs to be change to W10_2004 to work with current versions of the software. Or you have to downgrade.

**Comment by JayG30** [comment]
Yep, I was right. I downloaded the source and edited that line to W10_2004. Ran the powershell script to launch the GUI and now it works.

So please update the value so that it works wit the current version of IntuneWin32App.

**Comment by Romanitho** [comment]
Thanks for your investigation. Push a PR to get credited ;) this is your researches. If you don't have time, I can do it.

**Comment by JayG30** [comment]
> Thanks for your investigation. Push a PR to get credited ;) this is your researches. If you don't have time, I can do it.

[Done](https://github.com/Romanitho/WingetIntunePackager/pull/10)

**Comment by JayG30** [comment]
PR opened. Closing out issue.
